export const ADMIN_USERS_MOCK_DATA = [
  {
    userNo: 1,
    userId: 'test1',
    email: 'test1@gmail.com',
    userName: '테스트1',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 2,
    userId: 'test2',
    email: 'test2@gmail.com',
    userName: '테스트2',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 3,
    userId: 'test3',
    email: 'test3@gmail.com',
    userName: '테스트3',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 4,
    userId: 'test4',
    email: 'test4@gmail.com',
    userName: '강송희',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 5,
    userId: 'test5',
    email: 'test5@gmail.com',
    userName: '구교희',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
];
