export const ADMIN_USERS_MOCK_DATA = [
  {
    userNo: 1,
    userId: 'test1',
    email: 'test1@gmail.com',
    userName: '테스트1',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 2,
    userId: 'test2',
    email: 'test2@gmail.com',
    userName: '테스트2',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 3,
    userId: 'test3',
    email: 'test3@gmail.com',
    userName: '테스트3',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 4,
    userId: 'test4',
    email: 'test4@gmail.com',
    userName: '강송희',
    studentNo: 12345678,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 5,
    userId: 'test5',
    email: 'test5@gmail.com',
    userName: '구교희',
    studentNo: 87654321,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 6,
    userId: 'test6',
    email: 'test1@gmail.com',
    userName: '테스트6',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 7,
    userId: 'test7',
    email: 'test2@gmail.com',
    userName: '테스트7',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 8,
    userId: 'test8',
    email: 'test3@gmail.com',
    userName: '테스트8',
    studentNo: null,
    role: 'USER',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 9,
    userId: 'test9',
    email: 'test9@gmail.com',
    userName: '테스트9',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 10,
    userId: 'test10',
    email: 'test10@gmail.com',
    userName: '테스트10',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 11,
    userId: 'test11',
    email: 'test10@gmail.com',
    userName: '테스트11',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 12,
    userId: 'test12',
    email: 'test10@gmail.com',
    userName: '테스트12',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 13,
    userId: 'test13',
    email: 'test10@gmail.com',
    userName: '테스트13',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 14,
    userId: 'test14',
    email: 'test10@gmail.com',
    userName: '테스트14',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
  {
    userNo: 15,
    userId: 'test15',
    email: 'test10@gmail.com',
    userName: '테스트15',
    studentNo: null,
    role: 'ARTIST',
    userStatus: 'ACTIVE',
    signinTimestamp: '2025-05-14T19:47:46.137+00:00',
    signoutTimestamp: null,
    bannedTimestamp: null,
    cause: null,
  },
];
